
-- SCRIPT 1: CREACIÓN DE TABLESPACES
-- Curso: Base de Datos II - Ejercicio Ciclismo

-- 1. TABLESPACE PARA DATOS
CREATE TABLESPACE TBS_CICLISMO_DATA
DATAFILE 'C:\app\oracle\oradata\XE\tbs_ciclismo_data01.dbf' 
SIZE 50M
AUTOEXTEND ON 
NEXT 5M
MAXSIZE 200M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- 2. TABLESPACE TEMPORAL
CREATE TEMPORARY TABLESPACE TBS_CICLISMO_TEMP
TEMPFILE 'C:\app\oracle\oradata\XE\tbs_ciclismo_temp01.dbf'
SIZE 20M
AUTOEXTEND ON
NEXT 5M
MAXSIZE 100M;

-- 3. ASIGNAR TABLESPACES AL USUARIO
ALTER USER USR_CICLISMO 
DEFAULT TABLESPACE TBS_CICLISMO_DATA
TEMPORARY TABLESPACE TBS_CICLISMO_TEMP;

-- 4. OTORGAR CUOTA ILIMITADA
ALTER USER USR_CICLISMO QUOTA UNLIMITED ON TBS_CICLISMO_DATA;

-- Verificar tablespaces creados
SELECT tablespace_name, status, contents 
FROM dba_tablespaces 
WHERE tablespace_name LIKE 'TBS_CICLISMO%';

COMMIT;